Fix a bug for fmt variable initialization
fmt isn't properly initialized (because it is assigned in a switch).
Here is the error message from mcvs 2015:
... latexpp\latex.cpp(374): error C4703: potentially uninitialized local pointer variable 'fmt' used